# Run this file to simulate production environment in development (e.g. on your dev computer)

# Usage:
# COMPOSE_PROJECT_NAME=p1 docker-compose -f docker-compose-prod.yml build

version: '3.5'

services:
  nginx:
    build:
      context: .
      dockerfile: .docker/nginx/Dockerfile-prod
    image: ${COMPOSE_PROJECT_NAME}_nginx
    container_name: ${COMPOSE_PROJECT_NAME}_nginx
    ports:
      - 80:80
    networks:
      - default

  php-temp:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
      args:
        - APP_ENV=prod
    image: php_dev_temp

  php:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile-dist
      args:
        - APP_ENV=prod
    image: totea/php-for-symfony-prod:fpm-alpine
    container_name: ${COMPOSE_PROJECT_NAME}_php
    environment:
      - APP_ENV=prod
      - APP_SECRET=8f70994f2ae4009a5ae2d592ae645490
      - DATABASE_URL=mysql://develop_insecure:develop_insecure@mysql:3306/develop_${COMPOSE_PROJECT_NAME}
      - MAILER_URL=smtp://smtp.mailgun.org:25?encryption=tls&auth_mode=login&username=postmaster@terp.cz&password=91f4407775bba7429d21deb141ebf5f7-9b463597-66e72a2e
    networks:
      default:
        aliases:
          - fpm

networks:
  default:
    name: ${COMPOSE_PROJECT_NAME}
    driver: bridge